name: Flutter Build

# https://github.com/softprops/action-gh-release
on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  Flutter-Build:
    # https://docs.github.com/cn/actions/reference/workflow-syntax-for-github-actions
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        # https://github.com/actions/upload-release-asset/issues/16#issuecomment-662186555
        include:
          - os: ubuntu-latest
            platform: linux
            build_path: ./build/linux/x64/release/bundle/
            compress_cmd: tar -czvf linux-bundle.tar.gz *
            zip_name: linux-bundle.tar.gz
          - os: macos-latest
            platform: macos
            build_path: ./build/macos/Build/Products/Release/
            compress_cmd: zip macOS-Release.zip *
            zip_name: macOS-Release.zip
          - os: windows-latest
            platform: windows
            build_path: .\build\windows\runner\Release\
            compress_cmd: Compress-Archive * Windows-Release.zip
            zip_name: Windows-Release.zip

    steps:
      - name: Setup flutter
        uses: subosito/flutter-action@master
        with:
          channel: 'stable'

      - name: Flutter config enable desktop
        run: flutter config --enable-${{ matrix.platform }}-desktop

      - name: Checkout repo Vanilla-s-Lab/docper
        uses: actions/checkout@master

      - name: Linux - Setup CMake
        uses: jwlawson/actions-setup-cmake@master
        # https://www.edwardthomson.com/blog/github_actions_14_conditionals_with_a_matrix.html
        if: matrix.os == 'ubuntu-latest'

      - name: Linux - Install additional packages
        # https://github.com/flutter/flutter/issues/59750
        run: sudo apt update && sudo apt install clang ninja-build libgtk-3-dev -y
        if: matrix.os == 'ubuntu-latest'

      - name: Flutter build & Compress
        # https://www.cyberciti.biz/faq/how-to-create-tar-gz-file-in-linux-using-command-line/
        run: |
          flutter build ${{ matrix.platform }}
          cd ${{ matrix.build_path }} && ${{ matrix.compress_cmd }}

      - name: Release
        uses: softprops/action-gh-release@master
        with:
          files: ${{ matrix.zip_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
